server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
logging:
  level:
    root: warn
    com.buffll: info
  file:
    path: log/blog-prod-log